### ISSUE TITLE
Issues with openbox autostart

### ISSUE THREAD

**Issue by ggg377** [jmc-88/tint3#5] opened 2015-04-13 16:34 UTC
When autostarting with openbox, tray doesn't show and the panel panel turns black when clicking.

**Comment by jmc-88** [comment] 2015-04-13 19:34
A few questions:
- Can you confirm this happens on an ArchLinux system? (As your first report came from the comments on https://aur.archlinux.org/packages/tint3-cpp-git/)
- Are you using a compositor? I think I've seen a similar occurrence when tint3 gets launched prior to the compositor being active.
- Have you tried using a debug build (`-DCMAKE_BUILD_TYPE=Debug`)? If you are running one, you'll find a (possibly not so useful, at its current state...) debug log in `/tmp/tint3.dbg`.

**Comment by ggg377** [comment] 2015-04-14 07:54
1) I can confirm this happened on Arch Linux, 2) I'm not using a compositor, 3) I have not tried a debug build, I will try it out and let you know.

**Comment by ghost** [comment] 2015-04-14 09:25
Just to add my feedback, I'm also using openbox on Arch Linux, and I can't reproduce this. The panel seems to work equally well whether:
1) there is no compositor,
2) the compositor is started after the panel, or
3) the compositor is started before the panel.

The compositor I am using is compton.

@ggg377: Could you confirm whether the problem persists now that you've updated your imlib2 package? (https://bbs.archlinux.org/viewtopic.php?pid=1519579#p1519579)

Perhaps imlib2 was causing this problem too.

**Comment by jmc-88** [comment] 2015-04-15 22:08
@ggg377: in the forum thread linked by @WorMzy above you mentioned that "_[...] this resolved the issue_". Can I consider this bug fixed then, or is there more to it?

**Comment by ggg377** [comment] 2015-04-16 09:58
Hey, it resolved the issue for tint2. I haven't tested tint3 with the updated library yet. I'll let you know how it goes, but if it isn't reproducable in Openbox/Arch Linux you might as well close it.

**Comment by jmc-88** [comment] 2015-05-11 10:16
I haven't received further feedback, and can't reproduce the issue on my machine. I'm closing this bug, please reopen as needed.

**Closed as completed by jmc-88** 2015-05-11 10:16 UTC
Labels: bug
